name: NethrionTeams
version: '2.1.0'
main: com.nethrion.teams.NethrionTeamsPlugin
api-version: '1.21'
author: Nethrion
description: Lightweight teams, homes, rankings and wars.
commands:
  team:
    description: Manage your team.
    usage: /team
    aliases: [teams]
permissions:
  nethrionteams.team:
    default: true
