name: NethrionTeams
version: '2.6.0'
main: com.nethrion.teams.NethrionTeamsPlugin
api-version: '1.21'
commands:
  team:
    description: Manage teams
  war:
    description: War reward commands
    usage: /war claim
softdepend: [ProtocolLib]
permissions:
  nethrionteams.team:
    default: true
