package com.nethrion.teams;
import org.bukkit.Location;import org.bukkit.configuration.ConfigurationSection;import org.bukkit.configuration.file.YamlConfiguration;import org.bukkit.plugin.java.JavaPlugin;
import java.io.*;import java.util.*;
public final class TeamStorage {
 private final JavaPlugin plugin;private final File file;private YamlConfiguration data;
 public TeamStorage(JavaPlugin p){plugin=p;file=new File(p.getDataFolder(),"teams.yml");file.getParentFile().mkdirs();data=YamlConfiguration.loadConfiguration(file);}
 public Map<UUID,Team> loadTeams(){Map<UUID,Team> r=new LinkedHashMap<>();ConfigurationSection s=data.getConfigurationSection("teams");if(s==null)return r;
  for(String k:s.getKeys(false)){ConfigurationSection t=s.getConfigurationSection(k);if(t==null)continue;try{UUID id=UUID.fromString(k),o=UUID.fromString(t.getString("owner",""));Team x=new Team(id,t.getString("name",k),o,t.getBoolean("pvp"));
   for(String m:t.getStringList("members"))try{x.addMember(UUID.fromString(m));}catch(Exception ignored){}
   x.setStyle(t.getString("style.primary","#00E5FF"),t.getString("style.secondary","#7C4DFF"));x.setStats(t.getLong("stats.ores"),t.getLong("stats.mobs"),t.getLong("stats.players"),t.getLong("stats.trades"));
   ConfigurationSection h=t.getConfigurationSection("home");if(h!=null){var w=plugin.getServer().getWorld(h.getString("world",""));if(w!=null)x.setHome(new Location(w,h.getDouble("x"),h.getDouble("y"),h.getDouble("z"),(float)h.getDouble("yaw"),(float)h.getDouble("pitch")));}
   r.put(id,x);}catch(Exception e){plugin.getLogger().warning("Skipping invalid team entry "+k);}}return r;}
 public Map<UUID, TeamInvite> loadInvites(){Map<UUID,TeamInvite> r=new LinkedHashMap<>();ConfigurationSection s=data.getConfigurationSection("invites");if(s==null)return r;for(String k:s.getKeys(false))try{ConfigurationSection i=s.getConfigurationSection(k);UUID player=UUID.fromString(k),team=UUID.fromString(i.getString("team"));long expires=i.getLong("expires");if(expires>System.currentTimeMillis())r.put(player,new TeamInvite(team,expires));}catch(Exception ignored){}return r;}
 public List<TeamWar> loadWars(){List<TeamWar> r=new ArrayList<>();ConfigurationSection s=data.getConfigurationSection("wars");if(s==null)return r;for(String k:s.getKeys(false))try{ConfigurationSection w=s.getConfigurationSection(k);UUID id=UUID.fromString(k),creator=UUID.fromString(w.getString("creator"));List<UUID> ts=w.getStringList("targets").stream().map(UUID::fromString).toList();List<UUID> ac=w.getStringList("accepted").stream().map(UUID::fromString).toList();r.add(new TeamWar(id,creator,ts,ac));}catch(Exception ignored){}return r;}
 public synchronized void saveAll(Collection<Team> teams,Collection<TeamWar> wars,Map<UUID,TeamInvite> invites){data=new YamlConfiguration();for(Team t:teams){String b="teams."+t.getId();data.set(b+".name",t.getName());data.set(b+".owner",t.getOwner().toString());data.set(b+".members",t.getMembersSnapshot().stream().map(UUID::toString).toList());data.set(b+".pvp",t.isPvpEnabled());data.set(b+".style.primary",t.getPrimary());data.set(b+".style.secondary",t.getSecondary());long[] z=t.stats();data.set(b+".stats.ores",z[0]);data.set(b+".stats.mobs",z[1]);data.set(b+".stats.players",z[2]);data.set(b+".stats.trades",z[3]);Location h=t.getHome();if(h!=null&&h.getWorld()!=null){data.set(b+".home.world",h.getWorld().getName());data.set(b+".home.x",h.getX());data.set(b+".home.y",h.getY());data.set(b+".home.z",h.getZ());data.set(b+".home.yaw",h.getYaw());data.set(b+".home.pitch",h.getPitch());}}
  for(Map.Entry<UUID,TeamInvite> e:invites.entrySet()){if(e.getValue().expires()>System.currentTimeMillis()){String b="invites."+e.getKey();data.set(b+".team",e.getValue().teamId().toString());data.set(b+".expires",e.getValue().expires());}}
  for(TeamWar w:wars){String b="wars."+w.id();data.set(b+".creator",w.creator().toString());data.set(b+".targets",w.targets().stream().map(UUID::toString).toList());data.set(b+".accepted",w.accepted().stream().map(UUID::toString).toList());}
  try{data.save(file);}catch(IOException e){throw new IllegalStateException("Could not save team data",e);}}
 public static String normalize(String s){return s.trim().toLowerCase(Locale.ROOT);}
}