package com.nethrion.teams;
import org.bukkit.*;import org.bukkit.entity.Player;import org.bukkit.plugin.java.JavaPlugin;import java.util.*;
public final class TeamManager {
 private final JavaPlugin plugin;private final TeamStorage storage;private final Map<UUID,Team> teams=new LinkedHashMap<>();private final Map<String,UUID> names=new HashMap<>();private final Map<UUID,UUID> index=new HashMap<>();private final Map<UUID,TeamWar> wars=new LinkedHashMap<>();private final Map<UUID,TeamInvite> invites=new LinkedHashMap<>();private final int min,max;private final boolean defaultPvp;
 private static final Map<String,String[]> PALETTES=Map.of("aqua",new String[]{"#00E5FF","#7C4DFF"},"blue",new String[]{"#2196F3","#00E5FF"},"purple",new String[]{"#7C4DFF","#E040FB"},"gold",new String[]{"#FFD740","#FF6D00"},"green",new String[]{"#00E676","#69F0AE"},"red",new String[]{"#FF1744","#FF5252"},"pink",new String[]{"#FF4081","#E040FB"});
 public TeamManager(JavaPlugin p){plugin=p;storage=new TeamStorage(p);teams.putAll(storage.loadTeams());invites.putAll(storage.loadInvites());for (TeamWar war : storage.loadWars()) { wars.put(war.id(), war); }for(Team t:teams.values()){names.put(TeamStorage.normalize(t.getName()),t.getId());for(UUID u:t.getMembers())index.put(u,t.getId());}min=p.getConfig().getInt("settings.min-team-name-length",3);max=p.getConfig().getInt("settings.max-team-name-length",16);defaultPvp=p.getConfig().getBoolean("settings.default-pvp",false);}
 public synchronized void save(){storage.saveAll(teams.values(),wars.values(),invites);}
 public synchronized Team findByName(String n){UUID id=n==null?null:names.get(TeamStorage.normalize(n));return id==null?null:teams.get(id);} public synchronized Team findById(UUID id){return teams.get(id);} public synchronized Team findByPlayer(UUID u){UUID id=index.get(u);return id==null?null:teams.get(id);} public Team currentTeam(Player p){return findByPlayer(p.getUniqueId());}
 public boolean isValidTeamName(String n){return n!=null&&n.length()>=min&&n.length()<=max&&n.matches("[A-Za-z0-9_-]+");}
 public synchronized boolean createTeam(Player o,String n){if(!isValidTeamName(n)||findByName(n)!=null||index.containsKey(o.getUniqueId()))return false;Team t=new Team(UUID.randomUUID(),n,o.getUniqueId(),defaultPvp);teams.put(t.getId(),t);names.put(TeamStorage.normalize(n),t.getId());index.put(o.getUniqueId(),t.getId());save();return true;}
 public synchronized boolean rename(Player p,String n){Team t=ownerTeam(p);if(!isValidTeamName(n)||(findByName(n)!=null&&!findByName(n).getId().equals(t.getId())))return false;names.remove(TeamStorage.normalize(t.getName()));t.setName(n);names.put(TeamStorage.normalize(n),t.getId());save();return true;}
 public synchronized boolean setColor(Player p,String c){String[] x=PALETTES.get(c.toLowerCase(Locale.ROOT));if(x==null)return false;Team owner=ownerTeam(p);for(Team t:teams.values()){if(!t.getId().equals(owner.getId())&&x[0].equalsIgnoreCase(t.getPrimary())&&x[1].equalsIgnoreCase(t.getSecondary()))return false;}owner.setStyle(x[0],x[1]);save();return true;}
 public synchronized boolean setHome(Player p){ownerTeam(p).setHome(p.getLocation());save();return true;} public synchronized boolean deleteHome(Player p){ownerTeam(p).setHome(null);save();return true;}
 public synchronized boolean togglePvp(Player p){Team t=ownerTeam(p);t.setPvpEnabled(!t.isPvpEnabled());save();return t.isPvpEnabled();}
 public synchronized boolean canDamage(UUID a,UUID b){Team x=findByPlayer(a),y=findByPlayer(b);if(x==null||y==null||x!=y)return true;if(x.isPvpEnabled())return true;return isWarBetween(x.getId(),y.getId());}
 private boolean isWarBetween(UUID a,UUID b){return wars.values().stream().anyMatch(w->w.status()==TeamWar.Status.ACTIVE&&w.targets().contains(a)&&w.targets().contains(b));}
 public synchronized boolean leave(Player p){Team t=findByPlayer(p.getUniqueId());if(t==null)return false;index.remove(p.getUniqueId());t.removeMember(p.getUniqueId());if(t.getMembers().isEmpty())removeTeam(t);else if(t.getOwner().equals(p.getUniqueId()))t.setOwner(t.getMembers().iterator().next());save();return true;}
 private void removeTeam(Team t){teams.remove(t.getId());names.remove(TeamStorage.normalize(t.getName()));wars.values().removeIf(w->w.creator().equals(t.getId())||w.targets().contains(t.getId()));}
 public synchronized boolean disband(Player p){Team t=ownerTeam(p);for(UUID u:t.getMembers())index.remove(u);removeTeam(t);save();return true;}
 public synchronized Team ownerTeam(Player p){Team t=findByPlayer(p.getUniqueId());if(t==null||!t.getOwner().equals(p.getUniqueId()))throw new IllegalStateException("OWNER_ONLY");return t;}
 public synchronized List<String> teamNames(){return teams.values().stream().map(Team::getName).sorted(String.CASE_INSENSITIVE_ORDER).toList();}
 public List<String> formatMembers(Team t){return t.getMembers().stream().map(Bukkit::getOfflinePlayer).map(OfflinePlayer::getName).filter(Objects::nonNull).sorted(String.CASE_INSENSITIVE_ORDER).toList();}
 public synchronized boolean invitePlayer(Player owner,Player target){Team t=ownerTeam(owner);if(target.getUniqueId().equals(owner.getUniqueId()))throw new IllegalArgumentException("You cannot invite yourself.");if(index.containsKey(target.getUniqueId()))throw new IllegalArgumentException("That player is already in a team.");TeamInvite old=invites.get(target.getUniqueId());if(old!=null&&old.expires()>System.currentTimeMillis()&&old.teamId().equals(t.getId()))throw new IllegalArgumentException("That player already has your pending invite.");long minutes=Math.max(1,plugin.getConfig().getLong("settings.invite-expiry-minutes",10));invites.put(target.getUniqueId(),new TeamInvite(t.getId(),System.currentTimeMillis()+minutes*60000L));save();return true;}
 public synchronized boolean acceptInvite(Player player,String teamName){if(index.containsKey(player.getUniqueId()))throw new IllegalArgumentException("You are already in a team.");TeamInvite in=invites.get(player.getUniqueId());if(in==null||in.expires()<=System.currentTimeMillis()){invites.remove(player.getUniqueId());save();return false;}Team t=teams.get(in.teamId());if(t==null){invites.remove(player.getUniqueId());save();return false;}if(teamName!=null&&!t.getName().equalsIgnoreCase(teamName))return false;t.addMember(player.getUniqueId());index.put(player.getUniqueId(),t.getId());invites.remove(player.getUniqueId());save();return true;}
 public synchronized boolean denyInvite(Player player,String teamName){TeamInvite in=invites.get(player.getUniqueId());if(in==null||in.expires()<=System.currentTimeMillis()){invites.remove(player.getUniqueId());save();return false;}Team t=teams.get(in.teamId());if(t==null||(teamName!=null&&!t.getName().equalsIgnoreCase(teamName)))return false;invites.remove(player.getUniqueId());save();return true;}
 public synchronized Team pendingInviteTeam(UUID player){TeamInvite in=invites.get(player);if(in==null||in.expires()<=System.currentTimeMillis()){invites.remove(player);return null;}return teams.get(in.teamId());}
 public synchronized String teamTag(Player p){Team t=currentTeam(p);return t==null?"":t.getName();}
 public synchronized TeamWar inviteWar(Player p,List<Team> targets){Team creator=ownerTeam(p);LinkedHashSet<UUID> ids=new LinkedHashSet<>();ids.add(creator.getId());for(Team t:targets)if(t!=null&&!t.getId().equals(creator.getId()))ids.add(t.getId());if(ids.size()<2)throw new IllegalArgumentException("Need at least one other team.");if(wars.values().stream().anyMatch(w->w.status()==TeamWar.Status.PENDING&&(w.creator().equals(creator.getId())||w.targets().contains(creator.getId()))))throw new IllegalStateException("PENDING_WAR");TeamWar w=new TeamWar(UUID.randomUUID(),creator.getId(),ids,List.of(creator.getId()));wars.put(w.id(),w);save();return w;}
 public synchronized TeamWar acceptWar(Player p){Team t=ownerTeam(p);TeamWar w=wars.values().stream().filter(x->x.status()==TeamWar.Status.PENDING&&x.targets().contains(t.getId())&&!x.accepted().contains(t.getId())).findFirst().orElse(null);if(w==null)return null;w.accept(t.getId());save();return w;}
 public synchronized List<TeamWar> wars(){return List.copyOf(wars.values());}
 public Set<String> colors(){return PALETTES.keySet();}
}