package com.nethrion.teams;
import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import java.util.*;
public final class TeamCommand implements CommandExecutor,TabCompleter{
 private final TeamManager m;private final TeamDisplay d;public TeamCommand(TeamManager m,TeamDisplay d){this.m=m;this.d=d;}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player p))return true;if(a.length==0){msg(p,"/team create, invite, home, base, war");return true;}try{switch(a[0].toLowerCase()){
 case "create"-> {if(a.length==2&&m.createTeam(p,a[1]))ok(p,"Team created.");else msg(p,"/team create <name>");}
 case "invite"->invite(p,a);case "name"->{if(a.length==2&&m.rename(p,a[1])){d.refreshAll();ok(p,"Team renamed.");}else msg(p,"/team name <name>");}
 case "members"->members(p);case "list"->list(p,a);case "color"->{if(a.length==2&&m.setColor(p,a[1])){d.refreshAll();ok(p,"Team color updated.");}else msg(p,"/team color <color>");}
 case "sethome"->{m.setHome(p);ok(p,"Team home saved.");}case "home"->tp(p,false);case "delhome"->{m.deleteHome(p);ok(p,"Team home removed.");}
 case "setbase"->{m.setBase(p);ok(p,"Team base saved.");}case "base"->tp(p,true);
 case "pvp"->ok(p,"Team PvP "+(m.togglePvp(p)?"ON":"OFF"));case "leave"->{if(m.leave(p)){d.refreshAll();ok(p,"You left the team.");}else msg(p,"No team.");}case "disband"->{m.disband(p);d.refreshAll();ok(p,"Team disbanded.");}case "war"->war(p,a);default->msg(p,"Unknown command.");}}catch(IllegalStateException e){msg(p,e.getMessage().equals("OWNER_ONLY")?"Owner only.":"War request already pending.");}catch(IllegalArgumentException e){msg(p,e.getMessage());}return true;}
 private void invite(Player p,String[] a){if(a.length>=3&&(a[1].equalsIgnoreCase("accept")||a[1].equalsIgnoreCase("deny"))){boolean x=a[1].equalsIgnoreCase("accept")?m.acceptInvite(p,a[2]):m.denyInvite(p,a[2]);if(x){d.refresh(p);ok(p,a[1]+"ed.");}else msg(p,"No valid invite.");return;}if(a.length!=2){msg(p,"/team invite <player>");return;}Player q=Bukkit.getPlayerExact(a[1]);if(q==null){msg(p,"Player must be online.");return;}m.invitePlayer(p,q);ok(p,"Invite sent.");}
 private void tp(Player p,boolean base){Team t=m.currentTeam(p);if(t==null||(base?t.getBase():t.getHome())==null){msg(p,"No team "+(base?"base":"home")+" set.");return;}p.teleportAsync(base?t.getBase():t.getHome()).thenAccept(x->{if(x)ok(p,"Teleported.");});}
 private void members(Player p){Team t=m.currentTeam(p);if(t==null){msg(p,"No team.");return;}p.sendMessage(ChatColor.BOLD+t.getName()+" MEMBERS");for(UUID u:t.getMembers())p.sendMessage((u.equals(t.getOwner())?ChatColor.GOLD+"★ ":ChatColor.GRAY+"• ")+Optional.ofNullable(Bukkit.getOfflinePlayer(u).getName()).orElse("Unknown"));}
 private void list(Player p,String[] a){List<String> n=m.teamNames();int pg=1;try{if(a.length>1)pg=Integer.parseInt(a[1]);}catch(Exception ignored){}int from=(Math.max(1,pg)-1)*10;if(from>=n.size()){msg(p,"No teams on that page.");return;}for(int i=from;i<Math.min(from+10,n.size());i++)p.sendMessage("#"+(i+1)+" "+n.get(i));}
 private void war(Player p,String[] a){if(a.length<2){msg(p,"/team war invite|accept|history");return;}if(a[1].equalsIgnoreCase("invite")){List<Team> ts=new ArrayList<>();for(int i=2;i<a.length;i++){Team t=m.findByName(a[i]);if(t!=null)ts.add(t);}TeamWar w=m.inviteWar(p,ts);ok(p,"War invite sent. Expires in 90 seconds.");for(Team t:ts){Player o=Bukkit.getPlayer(t.getOwner());if(o!=null)o.sendMessage("War invite from "+m.findById(w.creator()).getName()+". Use /team war accept "+m.findById(w.creator()).getName());}}
 else if(a[1].equalsIgnoreCase("accept")){if(a.length!=3){msg(p,"/team war accept <team>");return;}TeamWar w=m.acceptWar(p,a[2]);if(w==null){msg(p,"No matching war invite.");return;}ok(p,"War accepted.");if(w.status()==TeamWar.Status.ACTIVE)announce(w);}
 else if(a[1].equalsIgnoreCase("history"))history(p);else msg(p,"Invalid war command.");}
 private void announce(TeamWar w){String names=w.teams().stream().map(m::findById).filter(Objects::nonNull).map(Team::getName).reduce((x,y)->x+" VS "+y).orElse("TEAM WAR");for(Player q:Bukkit.getOnlinePlayers())q.showTitle(net.kyori.adventure.title.Title.title(net.kyori.adventure.text.Component.text("⚔ TEAM WAR ⚔").decorate(net.kyori.adventure.text.format.TextDecoration.BOLD),net.kyori.adventure.text.Component.text(names)));}
 private void history(Player p){List<TeamWar> h=m.history(p);if(h.isEmpty()){msg(p,"You have never fought a war.");return;}for(TeamWar w:h){Team winner=m.findById(w.winner());p.sendMessage((winner==null?"No winner":winner.getName()+" won")+" • "+w.status());}}
 private void ok(Player p,String s){p.sendMessage(ChatColor.GREEN+s);}private void msg(Player p,String s){p.sendMessage(ChatColor.RED+s);}
 public List<String> onTabComplete(CommandSender s,Command c,String a,String[] x){if(x.length==1)return f(x[0],List.of("create","invite","name","members","list","color","sethome","home","delhome","setbase","base","pvp","leave","disband","war"));if(x.length==2&&x[0].equalsIgnoreCase("war"))return f(x[1],List.of("invite","accept","history"));if(x.length>=3&&x[0].equalsIgnoreCase("war")&&x[1].equalsIgnoreCase("invite"))return f(x[x.length-1],m.teamNames());if(x.length==3&&x[0].equalsIgnoreCase("war")&&x[1].equalsIgnoreCase("accept")){List<String> r=new ArrayList<>();if(s instanceof Player p)for(TeamWar w:m.pendingWarsFor(p)){Team t=m.findById(w.creator());if(t!=null)r.add(t.getName());}return f(x[2],r);}if(x.length==2&&x[0].equalsIgnoreCase("invite"))return f(x[1],List.of("accept","deny"));if(x.length==2&&x[0].equalsIgnoreCase("color"))return f(x[1],m.colors().stream().sorted().toList());return List.of();}
 private List<String> f(String q,List<String> v){return v.stream().filter(z->z.toLowerCase().startsWith(q.toLowerCase())).toList();}
}
