package com.nethrion.teams;
import org.bukkit.Location; import org.bukkit.configuration.ConfigurationSection; import org.bukkit.configuration.file.YamlConfiguration; import org.bukkit.plugin.java.JavaPlugin;
import java.io.*;import java.util.*;
public final class TeamStorage{
 private final JavaPlugin plugin; private final File file; private final YamlConfiguration data;
 public TeamStorage(JavaPlugin p){plugin=p;file=new File(p.getDataFolder(),"teams.yml");file.getParentFile().mkdirs();data=YamlConfiguration.loadConfiguration(file);}
 public Map<String,Team> loadTeams(){Map<String,Team> r=new LinkedHashMap<>();ConfigurationSection s=data.getConfigurationSection("teams");if(s==null)return r;for(String k:s.getKeys(false)){ConfigurationSection t=s.getConfigurationSection(k);if(t==null)continue;try{UUID o=UUID.fromString(t.getString("owner",""));Team x=new Team(t.getString("name",k),o,t.getBoolean("pvp"));for(String m:t.getStringList("members"))try{x.addMember(UUID.fromString(m));}catch(Exception ignored){}x.setColor(t.getString("color","AQUA"));x.setStats(t.getLong("stats.ores"),t.getLong("stats.mobs"),t.getLong("stats.players"),t.getLong("stats.trades"));ConfigurationSection h=t.getConfigurationSection("home");if(h!=null&&plugin.getServer().getWorld(h.getString("world",""))!=null)x.setHome(new Location(plugin.getServer().getWorld(h.getString("world")),h.getDouble("x"),h.getDouble("y"),h.getDouble("z"),(float)h.getDouble("yaw"),(float)h.getDouble("pitch")));r.put(normalize(x.getName()),x);}catch(Exception e){plugin.getLogger().warning("Skipping invalid team "+k);}}return r;}
 public Map<String,Map<UUID,Long>> loadRequestMap(String root){return new LinkedHashMap<>();}
 public void saveAll(Map<String,Team> teams,Map<String,Map<UUID,Long>> req,Map<String,Map<UUID,Long>> inv){data.set("teams",null);for(Team t:teams.values()){String b="teams."+normalize(t.getName());data.set(b+".name",t.getName());data.set(b+".owner",t.getOwner().toString());data.set(b+".members",t.getMembersSnapshot().stream().map(UUID::toString).toList());data.set(b+".pvp",t.isPvpEnabled());data.set(b+".color",t.getColor());long[] z=t.stats();data.set(b+".stats.ores",z[0]);data.set(b+".stats.mobs",z[1]);data.set(b+".stats.players",z[2]);data.set(b+".stats.trades",z[3]);Location h=t.getHome();if(h!=null&&h.getWorld()!=null){data.set(b+".home.world",h.getWorld().getName());data.set(b+".home.x",h.getX());data.set(b+".home.y",h.getY());data.set(b+".home.z",h.getZ());data.set(b+".home.yaw",h.getYaw());data.set(b+".home.pitch",h.getPitch());}}try{data.save(file);}catch(IOException e){throw new IllegalStateException("Could not save teams.yml",e);}}
 public static String normalize(String s){return s.trim().toLowerCase(Locale.ROOT);}
}