package com.nethrion.teams;
import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import java.util.*;
public final class TeamCommand implements CommandExecutor,TabCompleter{
 private final TeamManager m;private final TeamDisplay d;private static final String P=ChatColor.WHITE+"NethrionTeams "+ChatColor.DARK_GRAY+"• ";
 public TeamCommand(TeamManager m,TeamDisplay d){this.m=m;this.d=d;}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player p)){s.sendMessage("Players only.");return true;}if(a.length==0){help(p);return true;}try{String x=a[0].toLowerCase(Locale.ROOT);switch(x){
 case "create"->create(p,a);case "name"->rename(p,a);case "members"->members(p);case "list"->list(p,a);case "board"->board(p);case "color"->color(p,a);case "sethome"->{m.setHome(p);ok(p,"Team home saved.");}case "home"->home(p);case "delhome"->{m.deleteHome(p);ok(p,"Team home removed.");}case "pvp"->{boolean on=m.togglePvp(p);ok(p,"Team PvP "+(on?"ON":"OFF"));}case "info"->info(p,a);case "leave"->{if(m.leave(p)){d.refresh(p);ok(p,"You left your team.");}else err(p,"You're not in a team.");}case "disband"->{Team t=m.currentTeam(p);if(t==null)err(p,"You're not in a team.");else{List<UUID> u=t.getMembersSnapshot();m.disband(p);u.forEach(d::refreshIfOnline);ok(p,"Team disbanded.");}}case "war"->war(p,a);default->help(p);} }catch(IllegalStateException e){err(p,"Owner only.");}return true;}
 private void create(Player p,String[] a){if(a.length!=2){err(p,"/team create <name>");return;}if(m.createTeam(p,a[1])){d.refresh(p);ok(p,"Created team "+a[1]+".");}else err(p,"Invalid/taken name or you're already in a team.");}
 private void rename(Player p,String[] a){if(a.length!=2){err(p,"/team name <newName>");return;}if(m.rename(p,a[1])){d.refreshAll();ok(p,"Team renamed to "+a[1]+".");}else err(p,"Invalid or already used name.");}
 private void members(Player p){Team t=m.currentTeam(p);if(t==null){err(p,"You're not in a team.");return;}p.sendMessage(ChatColor.DARK_GRAY+"──── "+ChatColor.BOLD+t.getName()+" MEMBERS "+ChatColor.DARK_GRAY+"────");for(String n:m.formatMembers(t)){p.sendMessage((Bukkit.getOfflinePlayer(n).getUniqueId().equals(t.getOwner())?ChatColor.GOLD+"★ ":ChatColor.GRAY+"• ")+ChatColor.WHITE+n);}}
 private void list(Player p,String[] a){int page=1;if(a.length>1)try{page=Math.max(1,Integer.parseInt(a[1]));}catch(Exception ignored){}List<String> n=m.teamNames();int from=(page-1)*10;if(from>=n.size()){err(p,"No teams on that page.");return;}p.sendMessage(ChatColor.BOLD+"TEAMS "+ChatColor.DARK_GRAY+"("+n.size()+")");for(int i=from;i<Math.min(from+10,n.size());i++)p.sendMessage(ChatColor.GRAY+"#"+(i+1)+" "+ChatColor.WHITE+n.get(i));}
 private void board(Player p){List<Team> b=m.board();p.sendMessage(ChatColor.DARK_GRAY+"━━━━ "+ChatColor.BOLD+"TEAM BOARD "+ChatColor.DARK_GRAY+"━━━━");for(int i=0;i<b.size();i++){ChatColor c=i==0?ChatColor.GOLD:i==1?ChatColor.GRAY:i==2?ChatColor.GOLD:ChatColor.DARK_GRAY;p.sendMessage(c+"#"+(i+1)+" "+ChatColor.BOLD+b.get(i).getName());}}
 private void color(Player p,String[] a){if(a.length!=2){err(p,"/team color <aqua|blue|dark_purple|light_purple|gold|green|red|yellow>");return;}if(m.setColor(p,a[1].toUpperCase(Locale.ROOT))){d.refreshAll();ok(p,"Team color updated.");}else err(p,"Invalid color.");}
 private void home(Player p){Team t=m.currentTeam(p);if(t==null||t.getHome()==null){err(p,"No team home is set.");return;}if(p.teleport(t.getHome()))ok(p,"Teleported to team home.");else err(p,"Teleport failed.");}
 private void info(Player p,String[] a){Team t=a.length>1?m.findByName(a[1]):m.currentTeam(p);if(t==null){err(p,"Team not found.");return;}p.sendMessage(ChatColor.BOLD+t.getName());p.sendMessage(ChatColor.GRAY+"Members: "+ChatColor.WHITE+t.getMembers().size());p.sendMessage(ChatColor.GRAY+"Owner: "+ChatColor.WHITE+Bukkit.getOfflinePlayer(t.getOwner()).getName());}
 private void war(Player p,String[] a){if(a.length<2){err(p,"/team war invite <team...> | /team war accept");return;}m.ownerTeam(p);if(a[1].equalsIgnoreCase("invite")&&a.length>2){List<String> names=new ArrayList<>();for(int i=2;i<a.length;i++)if(m.findByName(a[i])!=null&&!a[i].equalsIgnoreCase(m.currentTeam(p).getName()))names.add(a[i]);if(names.isEmpty()){err(p,"No valid target teams.");return;}Bukkit.broadcastMessage(ChatColor.DARK_RED+""+ChatColor.BOLD+"⚔ TEAM WAR ⚔");Bukkit.broadcastMessage(ChatColor.RED+String.join(" VS ",names));ok(p,"War invitation declared to "+String.join(", ",names)+".");}else if(a[1].equalsIgnoreCase("accept"))ok(p,"War accepted.");else err(p,"Invalid war command.");}
 private void help(Player p){p.sendMessage(ChatColor.BOLD+"NETHRION TEAMS");p.sendMessage(ChatColor.GRAY+"/team create, name, members, list, board, color");p.sendMessage(ChatColor.GRAY+"/team sethome, home, delhome, info, leave, disband");p.sendMessage(ChatColor.GRAY+"/team war invite <team...> | accept");}
 private void ok(Player p,String s){p.sendMessage(P+ChatColor.GREEN+s);}private void err(Player p,String s){p.sendMessage(P+ChatColor.RED+s);}
 public List<String> onTabComplete(CommandSender s,Command c,String l,String[] a){List<String> r=new ArrayList<>();if(a.length==1)r.addAll(List.of("create","name","members","list","board","color","sethome","home","delhome","pvp","info","leave","disband","war","help"));else if(a.length==2&&(a[0].equalsIgnoreCase("info")||a[0].equalsIgnoreCase("war")))r.addAll(a[0].equalsIgnoreCase("war")?List.of("invite","accept"):m.teamNames());else if(a.length>=3&&a[0].equalsIgnoreCase("war"))r.addAll(m.teamNames());String q=a[a.length-1].toLowerCase(Locale.ROOT);return r.stream().filter(v->v.toLowerCase(Locale.ROOT).startsWith(q)).distinct().toList();}
}