package com.nethrion.teams;
import org.bukkit.*;import org.bukkit.entity.Player;import org.bukkit.inventory.ItemStack;import org.bukkit.Material;import org.bukkit.plugin.java.JavaPlugin;import java.util.*;
public final class TeamManager {
 private final JavaPlugin plugin;private final TeamStorage storage;private final Map<UUID,Team> teams=new LinkedHashMap<>();private final Map<String,UUID> names=new HashMap<>();private final Map<UUID,UUID> index=new HashMap<>();private final Map<UUID,TeamWar> wars=new LinkedHashMap<>();private final Map<UUID,TeamInvite> invites=new LinkedHashMap<>();private final int min,max;private final boolean defaultPvp;private final long inviteMs,warMs;
 private static final Map<String,String[]> PALETTES=Map.of("aqua",new String[]{"#00E5FF","#7C4DFF"},"blue",new String[]{"#2196F3","#00E5FF"},"purple",new String[]{"#7C4DFF","#E040FB"},"gold",new String[]{"#FFD740","#FF6D00"},"green",new String[]{"#00E676","#69F0AE"},"red",new String[]{"#FF1744","#FF5252"},"pink",new String[]{"#FF4081","#E040FB"});
 public TeamManager(JavaPlugin p){plugin=p;storage=new TeamStorage(p);teams.putAll(storage.loadTeams());invites.putAll(storage.loadInvites());for(TeamWar w:storage.loadWars())wars.put(w.id(),w);for(Team t:teams.values()){names.put(TeamStorage.normalize(t.getName()),t.getId());for(UUID u:t.getMembers())index.put(u,t.getId());}min=p.getConfig().getInt("settings.min-team-name-length",3);max=p.getConfig().getInt("settings.max-team-name-length",16);defaultPvp=p.getConfig().getBoolean("settings.default-pvp",false);inviteMs=90_000L;warMs=10L*24_000L*50L;}
 public synchronized void save(){storage.saveAll(teams.values(),wars.values(),invites);}
 public synchronized Team findByName(String n){UUID i=n==null?null:names.get(TeamStorage.normalize(n));return i==null?null:teams.get(i);}public synchronized Team findById(UUID i){return teams.get(i);}public synchronized Team findByPlayer(UUID u){UUID i=index.get(u);return i==null?null:teams.get(i);}public Team currentTeam(Player p){return findByPlayer(p.getUniqueId());}
 public boolean isValidTeamName(String n){return n!=null&&n.length()>=min&&n.length()<=max&&n.matches("[A-Za-z0-9_-]+");}
 public synchronized boolean createTeam(Player p,String n){if(!isValidTeamName(n)||findByName(n)!=null||index.containsKey(p.getUniqueId()))return false;Team t=new Team(UUID.randomUUID(),n,p.getUniqueId(),defaultPvp);teams.put(t.getId(),t);names.put(TeamStorage.normalize(n),t.getId());index.put(p.getUniqueId(),t.getId());save();return true;}
 public synchronized Team ownerTeam(Player p){Team t=currentTeam(p);if(t==null||!t.getOwner().equals(p.getUniqueId()))throw new IllegalStateException("OWNER_ONLY");return t;}
 public synchronized boolean rename(Player p,String n){Team t=ownerTeam(p);Team other=findByName(n);if(!isValidTeamName(n)||(other!=null&&!other.getId().equals(t.getId())))return false;names.remove(TeamStorage.normalize(t.getName()));t.setName(n);names.put(TeamStorage.normalize(n),t.getId());save();return true;}
 public synchronized boolean setColor(Player p,String c){String[] x=PALETTES.get(c.toLowerCase(Locale.ROOT));if(x==null)return false;Team o=ownerTeam(p);for(Team t:teams.values())if(!t.getId().equals(o.getId())&&t.getPrimary().equalsIgnoreCase(x[0])&&t.getSecondary().equalsIgnoreCase(x[1]))throw new IllegalArgumentException("That team color is already taken.");o.setStyle(x[0],x[1]);save();return true;}
 public synchronized boolean setHome(Player p){ownerTeam(p).setHome(p.getLocation());save();return true;}public synchronized boolean deleteHome(Player p){ownerTeam(p).setHome(null);save();return true;}
 public synchronized boolean setBase(Player p){ownerTeam(p).setBase(p.getLocation());save();return true;}
 public synchronized boolean togglePvp(Player p){Team t=ownerTeam(p);t.setPvpEnabled(!t.isPvpEnabled());save();return t.isPvpEnabled();}
 public synchronized boolean canDamage(UUID a,UUID b){Team x=findByPlayer(a),y=findByPlayer(b);if(x==null||y==null||!x.getId().equals(y.getId()))return true;return x.isPvpEnabled();}
 public synchronized List<String> teamNames(){return teams.values().stream().map(Team::getName).sorted(String.CASE_INSENSITIVE_ORDER).toList();}public Set<String> colors(){return PALETTES.keySet();}
 public synchronized boolean invitePlayer(Player o,Player target){Team t=ownerTeam(o);if(index.containsKey(target.getUniqueId()))throw new IllegalArgumentException("That player is already in a team.");invites.put(target.getUniqueId(),new TeamInvite(t.getId(),System.currentTimeMillis()+Math.max(1,plugin.getConfig().getLong("settings.invite-expiry-minutes",10))*60_000L));save();return true;}
 public synchronized boolean acceptInvite(Player p,String n){TeamInvite i=invites.get(p.getUniqueId());if(i==null||i.expires()<=System.currentTimeMillis()){invites.remove(p.getUniqueId());return false;}Team t=teams.get(i.teamId());if(t==null||!t.getName().equalsIgnoreCase(n)||index.containsKey(p.getUniqueId()))return false;t.addMember(p.getUniqueId());index.put(p.getUniqueId(),t.getId());invites.remove(p.getUniqueId());save();return true;}
 public synchronized boolean denyInvite(Player p,String n){TeamInvite i=invites.get(p.getUniqueId());Team t=i==null?null:teams.get(i.teamId());if(t==null||i.expires()<=System.currentTimeMillis()||!t.getName().equalsIgnoreCase(n))return false;invites.remove(p.getUniqueId());save();return true;}
 public synchronized Team pendingInviteTeam(UUID u){TeamInvite i=invites.get(u);return i!=null&&i.expires()>System.currentTimeMillis()?teams.get(i.teamId()):null;}
 public synchronized TeamWar inviteWar(Player p,List<Team> target){cleanupWars();Team c=ownerTeam(p);LinkedHashSet<UUID> ids=new LinkedHashSet<>();ids.add(c.getId());for(Team t:target)if(t!=null&&!t.getId().equals(c.getId()))ids.add(t.getId());if(ids.size()<2)throw new IllegalArgumentException("Need another team.");for(TeamWar w:wars.values())if(w.status()==TeamWar.Status.PENDING&&w.teams().contains(c.getId()))throw new IllegalStateException("PENDING_WAR");TeamWar w=TeamWar.pending(c.getId(),ids,System.currentTimeMillis(),inviteMs);wars.put(w.id(),w);save();return w;}
 public synchronized List<TeamWar> pendingWarsFor(Player p){Team t=ownerTeam(p);cleanupWars();return wars.values().stream().filter(w->w.status()==TeamWar.Status.PENDING&&w.teams().contains(t.getId())&&!w.accepted().contains(t.getId())).toList();}
 public synchronized TeamWar acceptWar(Player p,String teamName){Team t=ownerTeam(p);for(TeamWar w:pendingWarsFor(p)){Team creator=teams.get(w.creator());if(creator!=null&&creator.getName().equalsIgnoreCase(teamName)){w.accept(t.getId(),System.currentTimeMillis(),warMs);save();return w;}}return null;}
 public synchronized void cleanupWars(){long now=System.currentTimeMillis();boolean dirty=false;for(TeamWar w:wars.values()){TeamWar.Status before=w.status();w.expireInvite(now);w.expireWar(now);if(before!=w.status())dirty=true;}if(dirty)save();}
 public synchronized TeamWar activeWar(UUID team){cleanupWars();return wars.values().stream().filter(w->w.status()==TeamWar.Status.ACTIVE&&w.teams().contains(team)).findFirst().orElse(null);}
 public synchronized TeamWar recordWarKill(Player killer,Player victim){Team kt=currentTeam(killer),vt=currentTeam(victim);if(kt==null||vt==null||kt.getId().equals(vt.getId()))return null;TeamWar w=activeWar(kt.getId());if(w==null||!w.teams().contains(vt.getId()))return null;Set<UUID> opponents=new LinkedHashSet<>();for(UUID tid:w.teams())if(!tid.equals(kt.getId())){Team t=teams.get(tid);if(t!=null)opponents.addAll(t.getMembers());}if(w.recordKill(kt.getId(),victim.getUniqueId(),opponents,System.currentTimeMillis())){save();return w;}save();return null;}
 public synchronized List<TeamWar> history(Player p){Team t=currentTeam(p);if(t==null)return List.of();return wars.values().stream().filter(w->w.status()==TeamWar.Status.COMPLETED||w.status()==TeamWar.Status.EXPIRED).filter(w->w.teams().contains(t.getId())).sorted(Comparator.comparingLong(TeamWar::endedAt).reversed()).limit(10).toList();}
 public synchronized String claim(Player p){for(TeamWar w:wars.values())if(w.canClaim(p.getUniqueId())&&w.winner()!=null){Team win=teams.get(w.winner());if(win!=null&&win.contains(p.getUniqueId())){ItemStack reward=new ItemStack(p.getUniqueId().equals(win.getOwner())?Material.NETHER_STAR:Material.DIAMOND_BLOCK,p.getUniqueId().equals(win.getOwner())?1:5);Map<Integer,ItemStack> left=p.getInventory().addItem(reward);for(ItemStack x:left.values())p.getWorld().dropItemNaturally(p.getLocation(),x);w.markClaimed(p.getUniqueId());save();return "Reward claimed.";} }return "No war reward available.";}
 public synchronized boolean leave(Player p){Team t=currentTeam(p);if(t==null)return false;index.remove(p.getUniqueId());t.removeMember(p.getUniqueId());if(t.getMembers().isEmpty()){teams.remove(t.getId());names.remove(TeamStorage.normalize(t.getName()));}else if(t.getOwner().equals(p.getUniqueId()))t.setOwner(t.getMembers().iterator().next());save();return true;}
 public synchronized boolean disband(Player p){Team t=ownerTeam(p);for(UUID u:t.getMembers())index.remove(u);teams.remove(t.getId());names.remove(TeamStorage.normalize(t.getName()));save();return true;}
 public synchronized void addOre(UUID u){Team t=findByPlayer(u);if(t!=null)t.addOreMined(1);}public synchronized void addMob(UUID u){Team t=findByPlayer(u);if(t!=null)t.addMobKills(1);}public synchronized void addTrade(UUID u){Team t=findByPlayer(u);if(t!=null)t.addTrades(1);}public synchronized void addPlayerKill(UUID u){Team t=findByPlayer(u);if(t!=null)t.addPlayerKills(1);}
}
