package com.nethrion.teams;
import org.bukkit.*;import org.bukkit.configuration.*;import org.bukkit.configuration.file.*;import org.bukkit.plugin.java.JavaPlugin;
import java.io.*;import java.util.*;
public final class TeamStorage {
 private final JavaPlugin plugin; private final File file;
 public TeamStorage(JavaPlugin p){plugin=p;file=new File(p.getDataFolder(),"teams.yml");file.getParentFile().mkdirs();}
 private YamlConfiguration data(){return YamlConfiguration.loadConfiguration(file);}
 private static Location loc(JavaPlugin p,ConfigurationSection s){if(s==null)return null;World w=p.getServer().getWorld(s.getString("world",""));return w==null?null:new Location(w,s.getDouble("x"),s.getDouble("y"),s.getDouble("z"),(float)s.getDouble("yaw"),(float)s.getDouble("pitch"));}
 private static void loc(YamlConfiguration d,String b,Location l){if(l==null||l.getWorld()==null)return;d.set(b+".world",l.getWorld().getName());d.set(b+".x",l.getX());d.set(b+".y",l.getY());d.set(b+".z",l.getZ());d.set(b+".yaw",l.getYaw());d.set(b+".pitch",l.getPitch());}
 public Map<UUID,Team> loadTeams(){YamlConfiguration d=data();Map<UUID,Team> r=new LinkedHashMap<>();ConfigurationSection s=d.getConfigurationSection("teams");if(s==null)return r;for(String k:s.getKeys(false))try{ConfigurationSection x=s.getConfigurationSection(k);UUID id=UUID.fromString(k),o=UUID.fromString(x.getString("owner"));Team t=new Team(id,x.getString("name"),o,x.getBoolean("pvp"));for(String m:x.getStringList("members"))t.addMember(UUID.fromString(m));t.setStyle(x.getString("style.primary","#00E5FF"),x.getString("style.secondary","#7C4DFF"));t.setHome(loc(plugin,x.getConfigurationSection("home")));t.setBase(loc(plugin,x.getConfigurationSection("base")));t.setStats(x.getLong("stats.ores"),x.getLong("stats.playerKills"),x.getLong("stats.mobKills"),x.getLong("stats.trades"));r.put(id,t);}catch(Exception ignored){}return r;}
 public Map<UUID,TeamInvite> loadInvites(){YamlConfiguration d=data();Map<UUID,TeamInvite> r=new LinkedHashMap<>();ConfigurationSection s=d.getConfigurationSection("invites");if(s!=null)for(String k:s.getKeys(false))try{ConfigurationSection x=s.getConfigurationSection(k);long e=x.getLong("expires");if(e>System.currentTimeMillis())r.put(UUID.fromString(k),new TeamInvite(UUID.fromString(x.getString("team")),e));}catch(Exception ignored){}return r;}
 public List<TeamWar> loadWars(){YamlConfiguration d=data();List<TeamWar> r=new ArrayList<>();ConfigurationSection s=d.getConfigurationSection("wars");if(s==null)return r;for(String k:s.getKeys(false))try{ConfigurationSection x=s.getConfigurationSection(k);UUID id=UUID.fromString(k);List<UUID> ts=x.getStringList("teams").stream().map(UUID::fromString).toList();if(ts.isEmpty())ts=x.getStringList("targets").stream().map(UUID::fromString).toList();List<UUID> ac=x.getStringList("accepted").stream().map(UUID::fromString).toList();Map<UUID,Set<UUID>> km=new HashMap<>();ConfigurationSection ks=x.getConfigurationSection("kills");if(ks!=null)for(String tk:ks.getKeys(false))km.put(UUID.fromString(tk),new LinkedHashSet<>(ks.getStringList(tk).stream().map(UUID::fromString).toList()));r.add(new TeamWar(id,UUID.fromString(x.getString("creator")),ts,ac,x.getLong("created"),x.getLong("inviteExpires"),x.getLong("started"),x.getLong("expires"),x.getLong("ended"),TeamWar.Status.valueOf(x.getString("status","PENDING")),x.getString("winner")==null?null:UUID.fromString(x.getString("winner")),x.getString("loser")==null?null:UUID.fromString(x.getString("loser")),km,x.getStringList("claimed").stream().map(UUID::fromString).toList()));}catch(Exception ignored){}return r;}
 public synchronized void saveAll(Collection<Team> teams,Collection<TeamWar> wars,Map<UUID,TeamInvite> invites){YamlConfiguration d=new YamlConfiguration();for(Team t:teams){String b="teams."+t.getId();d.set(b+".name",t.getName());d.set(b+".owner",t.getOwner().toString());d.set(b+".members",t.getMembersSnapshot().stream().map(UUID::toString).toList());d.set(b+".pvp",t.isPvpEnabled());d.set(b+".style.primary",t.getPrimary());d.set(b+".style.secondary",t.getSecondary());loc(d,b+".home",t.getHome());loc(d,b+".base",t.getBase());d.set(b+".stats.ores",t.getOreMined());d.set(b+".stats.playerKills",t.getPlayerKills());d.set(b+".stats.mobKills",t.getMobKills());d.set(b+".stats.trades",t.getTrades());}long now=System.currentTimeMillis();for(var e:invites.entrySet())if(e.getValue().expires()>now){String b="invites."+e.getKey();d.set(b+".team",e.getValue().teamId().toString());d.set(b+".expires",e.getValue().expires());}for(TeamWar w:wars){String b="wars."+w.id();d.set(b+".creator",w.creator().toString());d.set(b+".teams",w.teams().stream().map(UUID::toString).toList());d.set(b+".accepted",w.accepted().stream().map(UUID::toString).toList());d.set(b+".created",w.createdAt());d.set(b+".inviteExpires",w.inviteExpiresAt());d.set(b+".started",w.startedAt());d.set(b+".expires",w.expiresAt());d.set(b+".ended",w.endedAt());d.set(b+".status",w.status().name());if(w.winner()!=null)d.set(b+".winner",w.winner().toString());d.set(b+".claimed",w.claimed().stream().map(UUID::toString).toList());for(var e:w.allKills().entrySet())d.set(b+".kills."+e.getKey(),e.getValue().stream().map(UUID::toString).toList());}try{d.save(file);}catch(IOException e){throw new IllegalStateException(e);}}
 public static String normalize(String s){return s.trim().toLowerCase(Locale.ROOT);}
}
