package com.nethrion.teams;
import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import java.util.*;
public final class TeamCommand implements CommandExecutor,TabCompleter{
 private final TeamManager m;private final TeamDisplay d;private static final String P=ChatColor.WHITE+"NethrionTeams "+ChatColor.DARK_GRAY+"• ";
 public TeamCommand(TeamManager m,TeamDisplay d){this.m=m;this.d=d;}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player p)){s.sendMessage("Players only.");return true;}if(a.length==0){help(p);return true;}try{switch(a[0].toLowerCase(Locale.ROOT)){
 case "create"->create(p,a);case "name"->rename(p,a);case "members"->members(p);case "list"->list(p,a);case "board"->board(p);case "color"->color(p,a);
 case "sethome"->{m.setHome(p);ok(p,"Team home saved.");}case "home"->home(p);case "delhome"->{m.deleteHome(p);ok(p,"Team home removed.");}
 case "pvp"->{boolean on=m.togglePvp(p);ok(p,"Team PvP "+(on?"ON":"OFF"));}case "info"->info(p,a);case "leave"->{if(m.leave(p)){d.refreshAll();ok(p,"You left your team.");}else err(p,"You're not in a team.");}
 case "disband"->{Team t=m.currentTeam(p);if(t==null)err(p,"You're not in a team.");else{m.disband(p);d.refreshAll();ok(p,"Team disbanded.");}}case "war"->war(p,a);default->help(p);}}catch(IllegalStateException e){err(p,e.getMessage().equals("PENDING_WAR")?"You already have a pending war invitation.":"Owner only.");}catch(IllegalArgumentException e){err(p,e.getMessage());}return true;}
 private void create(Player p,String[] a){if(a.length!=2){err(p,"/team create <name>");return;}if(m.createTeam(p,a[1])){d.refresh(p);ok(p,"Created team "+a[1]+".");}else err(p,"Invalid/taken name or you're already in a team.");}
 private void rename(Player p,String[] a){if(a.length!=2){err(p,"/team name <newName>");return;}if(m.rename(p,a[1])){d.refreshAll();ok(p,"Team renamed.");}else err(p,"Invalid or already used name.");}
 private void members(Player p){Team t=m.currentTeam(p);if(t==null){err(p,"You're not in a team.");return;}p.sendMessage(ChatColor.BOLD+t.getName()+" MEMBERS");for(UUID id:t.getMembersSnapshot()){String n=Optional.ofNullable(Bukkit.getOfflinePlayer(id).getName()).orElse(id.toString().substring(0,8));p.sendMessage((id.equals(t.getOwner())?ChatColor.GOLD+"★ ":ChatColor.GRAY+"• ")+n);}}
 private void list(Player p,String[] a){int page=1;try{if(a.length>1)page=Integer.parseInt(a[1]);}catch(Exception ignored){}page=Math.max(1,page);List<String> n=m.teamNames();int pages=Math.max(1,(n.size()+9)/10),from=(page-1)*10;if(from>=n.size()){err(p,"No teams on that page.");return;}p.sendMessage(ChatColor.BOLD+"TEAMS "+ChatColor.GRAY+"Page "+page+"/"+pages);for(int i=from;i<Math.min(from+10,n.size());i++)p.sendMessage(ChatColor.GRAY+"#"+(i+1)+" "+n.get(i));}
 private void board(Player p){List<Team>b=m.board();p.sendMessage(ChatColor.BOLD+"TEAM BOARD");for(int i=0;i<b.size();i++)p.sendMessage((i==0?ChatColor.GOLD:i==1?ChatColor.GRAY:i==2?ChatColor.GOLD:ChatColor.DARK_GRAY)+"#"+(i+1)+" "+b.get(i).getName());}
 private void color(Player p,String[] a){if(a.length!=2){err(p,"/team color <color>");return;}if(m.setColor(p,a[1])){d.refreshAll();ok(p,"Team style updated.");}else err(p,"Invalid color.");}
 private void home(Player p){Team t=m.currentTeam(p);if(t==null||t.getHome()==null){err(p,"No team home is set.");return;}p.teleportAsync(t.getHome()).thenAccept(v->{if(v)ok(p,"Teleported to team home.");else err(p,"Teleport failed.");});}
 private void info(Player p,String[] a){Team t=a.length>1?m.findByName(a[1]):m.currentTeam(p);if(t==null){err(p,"Team not found.");return;}p.sendMessage(ChatColor.BOLD+t.getName());p.sendMessage(ChatColor.GRAY+"Members: "+ChatColor.WHITE+t.getMembers().size());p.sendMessage(ChatColor.GRAY+"Owner: "+ChatColor.WHITE+Optional.ofNullable(Bukkit.getOfflinePlayer(t.getOwner()).getName()).orElse("Unknown"));}
 private void war(Player p,String[] a){if(a.length<2){err(p,"/team war invite <team...> | /team war accept");return;}if(a[1].equalsIgnoreCase("invite")){if(a.length<3){err(p,"Add at least one team.");return;}List<Team> ts=new ArrayList<>();for(int i=2;i<a.length;i++){Team t=m.findByName(a[i]);if(t!=null)ts.add(t);}TeamWar w=m.inviteWar(p,ts);ok(p,"War invitation sent to "+(w.targets().size()-1)+" team(s).");}
 else if(a[1].equalsIgnoreCase("accept")){TeamWar w=m.acceptWar(p);if(w==null){err(p,"No pending war invitation.");return;}ok(p,"War invitation accepted.");if(w.status()==TeamWar.Status.ACTIVE){String names=w.targets().stream().map(m::findById).filter(Objects::nonNull).map(Team::getName).reduce((x,y)->x+" VS "+y).orElse("TEAM WAR");for(Player q:Bukkit.getOnlinePlayers())q.showTitle(net.kyori.adventure.title.Title.title(net.kyori.adventure.text.Component.text("⚔ TEAM WAR ⚔",net.kyori.adventure.text.format.NamedTextColor.RED).decorate(net.kyori.adventure.text.format.TextDecoration.BOLD),net.kyori.adventure.text.Component.text(names,net.kyori.adventure.text.format.NamedTextColor.GOLD)));}}
 else err(p,"Invalid war command.");}
 private void help(Player p){p.sendMessage(ChatColor.BOLD+"NETHRION TEAMS");p.sendMessage("/team create, name, members, list, board, color");p.sendMessage("/team sethome, home, delhome, info, leave, disband");p.sendMessage("/team war invite <team...> | accept");}
 private void ok(Player p,String s){p.sendMessage(P+ChatColor.GREEN+s);}private void err(Player p,String s){p.sendMessage(P+ChatColor.RED+s);}
 public List<String> onTabComplete(CommandSender s,Command c,String a,String[] x){if(x.length==1)return filter(x[0],List.of("create","name","members","list","board","color","sethome","home","delhome","pvp","info","leave","disband","war"));if(x.length==2&&x[0].equalsIgnoreCase("color"))return filter(x[1],m.colors().stream().sorted().toList());if(x.length==2&&x[0].equalsIgnoreCase("war"))return filter(x[1],List.of("invite","accept"));if(x.length>=3&&x[0].equalsIgnoreCase("war")&&x[1].equalsIgnoreCase("invite"))return filter(x[x.length-1],m.teamNames());if(x.length==2&&x[0].equalsIgnoreCase("info"))return filter(x[1],m.teamNames());return List.of();}
 private List<String> filter(String q,List<String> v){return v.stream().filter(z->z.toLowerCase().startsWith(q.toLowerCase())).toList();}
}